spring.application.name=surest_member_management

spring.datasource.url=jdbc:postgresql://localhost:5432/surest_db
spring.datasource.username=postgres
spring.datasource.password=Evry@25
spring.jpa.hibernate.ddl-auto=validate
    # Flyway will manage schema, not Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true