spring.application.name=surest_member_management

spring.datasource.url=jdbc:postgresql://localhost:5432/surest_db
spring.datasource.username=postgres
spring.datasource.password=Evry@25
spring.jpa.hibernate.ddl-auto=validate
    # Flyway will manage schema, not Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
app.secret.key=aVeryLongSecretKeyThatIsAtLeast64CharactersLongForHS512Algorithm1234567890
app.jwt-expiration-milliseconds=3600000

#Swagger
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Log
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.surest=DEBUG
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#Redis
spring.cache.type= redis
spring.data.redis.host= localhost
spring.data.redis.port= 6379

#Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000